# -*- coding: utf-8 -*-
"""21futura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ciUsgqoCCg2lGhdNtR4yvZMCLXNdwp6p
"""

print('basil')

x=20
type(x)

a=2
a=str(a)
type(a)

str='good morning'
print(str)

str='hello world gohsjsksh   skhshbkshs '
print('world'in str)

str='hello futuraaa...welcome'
print('hai'in str)

i=1
while(i<=10):
  print(i)
  i += 1

for i in range(1,10):
  print(i)

for i in range(10,0,-1):

  print(i)